---

version: '3.3'
services:
  backend:
    build:
      context: ./backend/
    container_name: 'backend'
    hostname: 'backend'
    restart: always
    ports:
      - 8000:8000

  # frontend:
  #   build:
  #     context: ./frontend/
  #   container_name: 'frontend'
  #   hostname: 'frontend'
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - backe
  #   links:
  #     - backend
  #   environment:
  #     - NEXT_PUBLIC_API_URL='http://localhost:8000'
