---

version: '3.3'
services:
  backend:
    build:
      context: ./backend/
    container_name: 'backend'
    hostname: 'backend'
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend/
    container_name: 'frontend'
    hostname: 'frontend'
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    links:
      - backend
